# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
 
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-env name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}

          echo "$SOURCE_BRANCH"
          echo $SOURCE_BRANCH
