# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
 
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: |
          echo ::set-env name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}

          echo ${{ env.GITHUB_SHA_SHORT }}
          echo $SOURCE_BRANCH
      - name: Set env
        run: echo ::set-env name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA | cut -c 1-6)
      - name: Test
        run: echo $GITHUB_SHA_SHORT
